FROM alpine:3.22@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce
RUN apk add --no-cache ca-certificates curl
COPY edge/ddns/run.sh /usr/local/bin/smacx-ddns
RUN chmod 0555 /usr/local/bin/smacx-ddns
ENTRYPOINT ["/usr/local/bin/smacx-ddns"]
