import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const source = await readFile(new URL('../portal/Smacx.Portal.Client/wwwroot/js/ai-activity.js', import.meta.url), 'utf8');
const { applyEvent } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const state = { items: new Map(), seen: new Set() };
const event = (id, payload) => ({event_id:id, recorded_unix:1, correlation:{run_id:'run',request_id:'request',call_id:'call'},payload});
const delta = event('1',{type:'response_delta',chunks:[{choices:[{delta:{content:'Answer',reasoning_content:'Thought'}}]}]});
applyEvent(state,delta); applyEvent(state,delta);
applyEvent(state,event('stream-call',{type:'response_delta',chunks:[{choices:[{delta:{tool_calls:[{index:0,id:'call',function:{name:'smac_world',arguments:'{'}}]}}]}]}));
applyEvent(state,event('stream-args',{type:'response_delta',chunks:[{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'}'}}]}}]}]}));
assert.equal([...state.items.values()][0].tools.get('call').arguments,'{}');
applyEvent(state,event('2',{type:'response_finished',complete:true}));
applyEvent(state,event('3',{type:'tool_requested',managed_name:'smac_world',arguments:{}}));
applyEvent(state,event('4',{type:'tool_returned',managed_name:'smac_world',content:'{}'}));
const item = [...state.items.values()][0];
assert.equal(state.items.size,1); assert.equal(item.text,'Answer'); assert.equal(item.thinking,'Thought');
assert.equal(item.tools.size,1); assert.equal([...item.tools.values()][0].status,'Returned');
applyEvent(state,{...delta,event_id:'5',correlation:{run_id:'new-run',request_id:'request'}});
assert.equal(state.items.size,2);
console.log('PASS: duplicate events ignored, calls updated in place, recovery runs separated');
